[package]
name = "catori-core"
version = "0.1.0"
authors = ["tupshin"]
edition = "2018"

[dependencies]
fixedvec = "0.2.4"
# pom="3.1.0"
serde-lexpr = "0.1.1"
lexpr = "0.2.4"
log = "0.4.8"
serde = "1.0.105"
serde_derive = "1.0.105"

[lib]
name="catori_core"

# [[bin]]
# name="test"
